use crate::{cache,config::ResolverConfig,parser,workspace::Workspaces};
use anyhow::{Context,Result};use petgraph::{algo::kosaraju_scc,graph::NodeIndex,Graph};use rayon::prelude::*;use serde::{Deserialize,Serialize};use std::{collections::HashMap,fs,path::{Path,PathBuf}};use walkdir::WalkDir;
#[derive(Clone,Debug,Deserialize,Serialize)]pub struct AnalysisReport{pub files_scanned:usize,pub source_files:usize,pub dependencies:usize,pub cycles:Vec<Vec<String>>,pub nodes:Vec<String>,pub edges:Vec<DependencyEdge>,pub lines:HashMap<String,usize>}
#[derive(Clone,Debug,Deserialize,Serialize)]pub struct DependencyEdge{pub from:String,pub to:String}
pub fn analyze(root:&Path)->Result<AnalysisReport>{let root=root.canonicalize().with_context(||format!("cannot open {}",root.display()))?;if let Some(report)=cache::load(&root){return Ok(report);}let report=analyze_uncached(&root)?;cache::save(&root,&report);Ok(report)}
fn analyze_uncached(root:&Path)->Result<AnalysisReport>{let config=ResolverConfig::load(root);let workspaces=Workspaces::discover(root);let mut files=Vec::new();let mut files_scanned=0;for entry in WalkDir::new(root).into_iter().filter_entry(|e|{let n=e.file_name().to_string_lossy();!matches!(n.as_ref(),"node_modules"|".git"|"dist"|"build"|".next"|".nuxt"|"coverage"|"target")}){let entry=entry?;if !entry.file_type().is_file(){continue;}files_scanned+=1;if is_source(entry.path()){files.push(entry.path().to_path_buf());}}
let parsed=files.par_iter().map(|f|{let c=fs::read_to_string(f).unwrap_or_default();(f.clone(),c.lines().count(),parser::imports(f,&c))}).collect::<Vec<_>>();let mut graph=Graph::<PathBuf,()>::new();let mut indexes=HashMap::<PathBuf,NodeIndex>::new();for f in &files{indexes.insert(f.clone(),graph.add_node(f.clone()));}let mut edges=Vec::new();let mut lines=HashMap::new();for(file,line_count,imports)in parsed{lines.insert(relative(root,&file),line_count);for spec in imports{if let Some(target)=resolve_import(root,&file,&spec,&config,&workspaces){if let(Some(&from),Some(&to))=(indexes.get(&file),indexes.get(&target)){graph.add_edge(from,to,());edges.push(DependencyEdge{from:relative(root,&file),to:relative(root,&target)});}}}}let cycles=kosaraju_scc(&graph).into_iter().filter(|g|g.len()>1).map(|g|g.into_iter().map(|n|relative(root,&graph[n])).collect()).collect();let nodes=files.iter().map(|p|relative(root,p)).collect();Ok(AnalysisReport{files_scanned,source_files:files.len(),dependencies:edges.len(),cycles,nodes,edges,lines})}
fn relative(root:&Path,path:&Path)->String{path.strip_prefix(root).unwrap_or(path).display().to_string()}fn is_source(path:&Path)->bool{matches!(path.extension().and_then(|e|e.to_str()),Some("ts"|"tsx"|"js"|"jsx"|"vue"|"mjs"|"cjs"))}
fn resolve_import(root:&Path,source:&Path,spec:&str,config:&ResolverConfig,workspaces:&Workspaces)->Option<PathBuf>{if spec.starts_with('.') {return resolve_candidate(&source.parent()?.join(spec));}for(alias,targets)in &config.paths{let wildcard=alias.strip_suffix('*');let suffix=wildcard.and_then(|prefix|spec.strip_prefix(prefix));if suffix.is_none()&&alias!=spec{continue;}for target in targets{let mapped=suffix.map_or_else(||target.clone(),|s|target.replace('*',s));let base=config.base_url.as_deref().map(|p|root.join(p)).unwrap_or_else(||root.to_path_buf());if let Some(found)=resolve_candidate(&base.join(mapped)){return Some(found);}}}workspaces.resolve(spec).and_then(|p|resolve_candidate(&p))}
fn resolve_candidate(base:&Path)->Option<PathBuf>{const EXTS:[&str;7]=["ts","tsx","js","jsx","vue","mjs","cjs"];if base.is_file(){return base.canonicalize().ok();}for ext in EXTS{let c=base.with_extension(ext);if c.is_file(){return c.canonicalize().ok();}}if base.is_dir(){for ext in EXTS{let c=base.join(format!("index.{ext}"));if c.is_file(){return c.canonicalize().ok();}}}None}
